[package]
name = "sd-core-ai"
version = "0.1.0"
authors = ["Jamie Pine <jamie@spacedrive.com>"]
readme = "README.md"
rust-version = "1.75"
license = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
# Inner Core Sub-crates
sd-core-prisma-helpers = { path = "../prisma-helpers" }
sd-core-sync = { path = "../sync" }

# Spacedrive Sub-crates
sd-prisma = { path = "../../../crates/prisma" }
sd-core-prompt-derive = { path = "../prompt_derive" }
sd-utils = { path = "../../../crates/utils" }

# Workspace dependencies
chrono = { workspace = true, features = ["serde"] }
prisma-client-rust = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tracing = { workspace = true }
reqwest = { workspace = true }
chromadb = "0.5.0"
once_cell.workspace = true
paste = "1.0.15"
convert_case = "0.6.0"
inventory = "0.3.0"
serde_json.workspace = true
futures.workspace = true
async-stream = "0.3.5"
colored = "2.1.0"
lazy_static = "1.5.0"
ctor = "0.2.8"
expand = "0.3.0"
typify = "0.1.0"
schemars = "0.8.21"
ollama-rs = "0.2.0"

[target.'cfg(windows)'.dependencies]
winapi-util = "0.1.8"
