[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.0.1"
actix-web-actors = "4.1.0"
sdcore = { path = "../../core" }
serde = "1.0.136"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["sync", "rt"] }
