[package]
name = "spacedrive"
version = "0.1.0"
description = "The next gen private virtual filesystem."
authors = ["NerdHouse, Inc.", "Jamie Pine"]
license = ""
repository = "https://github.com/jamiepine/spacedrive"
default-run = "spacedrive"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }
swift-rs = "0.2.3"

[dependencies]
# Project dependencies
tauri = { version = "1.0.0-rc.6", features = ["api-all", "macos-private-api"] }
sdcore = { path = "../../../core" }
# tauri-plugin-shadows = { git = "https://github.com/tauri-apps/tauri-plugin-shadows", features = ["tauri-impl"] }

# Universal Dependencies
anyhow = "1.0.44"
log = "0.4.14"
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
strum = { version = "0.21.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
rebind = "0.2.1"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
cargo-edit = "0.8.0"
sha256 = "1.0.2"
once_cell = "1.8.0"
int-enum = "0.4.0"
async-std = "1.10.0"
tokio = { version = "1.17.0", features = ["sync"] }
lazy_static = "1.4.0"
window-shadows = "0.1.2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
