[package]
name    = "sd-core-cloud-services"
version = "0.1.0"

edition = "2021"

[dependencies]
# First party dependencies
sd-cloud-schema = { workspace = true }
sd-crypto       = { path = "../../../crates/crypto" }
sd-utils        = { path = "../../../crates/utils" }

# Workspace dependencies
base64              = { workspace = true }
blake3              = { workspace = true }
chrono              = { workspace = true, features = ["serde"] }
flume               = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
reqwest             = { workspace = true, features = ["json", "native-tls-vendored"] }
rspc                = { workspace = true }
serde               = { workspace = true, features = ["derive"] }
serde_json          = { workspace = true }
thiserror           = { workspace = true }
tokio               = { workspace = true, features = ["sync", "time"] }
tracing             = { workspace = true }
zeroize             = { workspace = true }

# External dependencies
iroh-base                = { version = "0.23.0", features = ["key"] }
postcard                 = { version = "1.0.8", features = ["use-std"] }
quic-rpc                 = { version = "0.12.0", features = ["quinn-transport"] }
quinn                    = { package = "iroh-quinn", version = "=0.11.3" }
reqwest-middleware       = { version = "0.3", features = ["json"] }
reqwest-retry            = "0.6"
rustls                   = { version = "0.23", default-features = false, features = ["ring"] }
rustls-platform-verifier = "0.3.3"


[dev-dependencies]
tokio = { workspace = true, features = ["rt", "sync", "time"] }
