[package]
name = "sdcorelib"
version = "0.1.0"
description = "The next gen private virtual filesystem."
authors = ["NerdHouse, Inc.", "Jamie Pine"]
license = ""
repository = "https://github.com/jamiepine/spacedrive"
edition = "2018"

[dependencies]
swift-rs = "0.2.3"
hotwatch = "0.4.6"
hostname = "0.3.1"
# Universal Dependencies
anyhow = "1.0.44"
log = "0.4.14"
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.0", features = ["serde"] }
strum = { version = "0.21.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
rebind = "0.2.1"
data-encoding = "2.3.2"
ring = "0.17.0-alpha.10"
cargo-edit = "0.8.0"
sha256 = "1.0.2"
once_cell = "1.8.0"
int-enum = "0.4.0"
# Project dependencies
ts-rs = "6.1"
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust.git", branch = "master" }
walkdir = "^2.3.2"
bytesize = "1.1.0"
env_logger = "0.9.0"
libp2p = "0.43.0"
config = {version = "0.12", features = ["toml"]}
lazy_static = "1.4.0"
uuid = "0.8"
thumbnailer = "0.4.0"
mime = "0.3.16"
sysinfo = "0.23.5"
thiserror = "1.0.30"

tokio = { version = "1.17.0", features = ["sync", "rt"] }
include_dir = {version = "0.7.2", features = ["glob"]}
