name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - new-ci
    paths-ignore:
      - '**/.md'
  workflow_dispatch:

jobs:
  pnpm-cache:
    name: Cache PNPM Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: [pnpm-cache]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      # - name: Cache pnpm dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.pnpm-store
      #     key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       pnpm-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Perform typechecks
        run: pnpm -r exec tsc

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    needs: [pnpm-cache]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Desktop
        run: pnpm desktop build

      - name: Build Web
        run: pnpm web build

  build-core:
    name: Build core (${{ matrix.platform }})
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c

      - name: Build prisma-cli
        run: cargo build

      - name: Build core-derive
        run: cargo build -p core-derive --release

      - name: Generate Primsa client
        working-directory: core
        run: cargo prisma generate

      - name: Build core
        run: cargo build -p core --release
