name: CI (Desktop) 
on:
  pull_request:
  push:
    branches:
      - main
      - new-ci
    paths-ignore:
      - '**/.md'
  workflow_dispatch:

jobs:
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Perform typechecks
        run: pnpm -r exec tsc

  build-js:
    name: Build JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Desktop
        run: pnpm desktop build

      - name: Build Web
        run: pnpm web build
  
  build-all:
    name: Build desktop (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install desktop dependencies
        uses: ./.github/actions/install-desktop-deps
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c
        with:
          sharedKey: all-${{ matrix.platform }} 
       
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  build-desktop:
    name: Build desktop (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install desktop dependencies
        uses: ./.github/actions/install-desktop-deps
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c
        with:
          sharedKey: all-${{ matrix.platform }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.6

      - name: Install pnpm dependencies
        run: pnpm i --frozen-lockfile

      - name: Generate Primsa client
        working-directory: core
        run: cargo prisma generate

      - name: Build frontend
        run: pnpm desktop build

      - name: Build
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: apps/desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifacts
        uses: ./.github/actions/publish-desktop-artifacts
