name: Update Org README

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPOS_PAT }}
        with:
          source_file: 'README.md'
          destination_repo: 'spacedrive/.github'
          destination_folder: '.'
          user_email: 'actions@spacedrive.app'
          user_name: 'actions'
          commit_message: 'Update README'